### ISSUE TITLE
Problems with OH 3.4.2

### ISSUE THREAD

**Issue by ModuloFS** [docbender/openHAB-SimpleBinary#12]
Hello,

i have problems to get the Binding running with OH 3.4.2. If i configure a Bridge and a Thing with textual configuration (an configuration over the Web interface i get the same errors):

`Bridge simplebinary:uart_bridge:UART_RF_Bridge "UART_RF_Bridge"  [ port="/dev/ttyAMA0", baudRate="115200" ] {
    Thing generic_device rollers "Rollershutters" {
        Channels:
            Type chRollershutter: DG_Balkon [ commandAddress="1:3" ]
    }
}`

If i enable the Bridge, it switches to online. If i endable the Thing i get some errors. You may see the log of this behaviour below:

`2023-03-05 09:18:00.016 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'Simplebinary.things'
2023-03-05 09:18:16.298 [INFO ] [andler.SimpleBinaryUartBridgeHandler] - UART_RF_Bridge - Current charset UTF-8
2023-03-05 09:18:32.952 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.simplebinary.internal.handler.SimpleBinaryGenericHandler@15f4482': null
java.lang.NullPointerException: null
	at org.openhab.binding.simplebinary.internal.handler.SimpleBinaryBridgeHandler.updateConfig(SimpleBinaryBridgeHandler.java:300) ~[?:?]
	at org.openhab.binding.simplebinary.internal.handler.SimpleBinaryGenericHandler.initialize(SimpleBinaryGenericHandler.java:106) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-03-05 09:18:32.973 [ERROR] [core.thing.internal.ThingManagerImpl] - Exception occurred while initializing handler of thing 'simplebinary:generic_device:UART_RF_Bridge:rollers': null
java.lang.NullPointerException: null
	at org.openhab.binding.simplebinary.internal.handler.SimpleBinaryBridgeHandler.updateConfig(SimpleBinaryBridgeHandler.java:300) ~[?:?]
	at org.openhab.binding.simplebinary.internal.handler.SimpleBinaryGenericHandler.initialize(SimpleBinaryGenericHandler.java:106) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:154) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by docbender** [comment]
There was a problem with command-only channels during initialization. It is fixed in the new release:
https://github.com/docbender/openHAB-SimpleBinary/releases/download/3.4%2C1/org.openhab.binding.simplebinary-3.4.0.jar

**Comment by ModuloFS** [comment]
Wow, fast response!! I will give it a try tomorrow.

**Comment by ModuloFS** [comment]
Ok, just tried the new version and it is working. Thank you for your fast work! 
Just a hint, maybe it is normal behaviour, but if i store the Things file with Bridge-, Thing- and Channel-definition for the first time, the Bridge is not initializing and stays in the UNINIZIALIZED state. I have to disable and then enable the Bridge in the Web interface manually. After this process the Bridge and the Thing switches to online. 

Btw you named the current released version 3.4.0 i do not know if this was your intention because the release itselve is named 3.4.1.
